### ISSUE TITLE
Error on suggested import 

### ISSUE THREAD

**Issue by horikx** [joshgillies/node-matrix-bundler-cli#1]
Your examples say to try using: 

```
matrix-bundler ./files ./files.tgz
matrix-bundler --entry ./files --link 2 --unrestricted --output ./files.tgz
```

after a global install.

On running these examples on windows, I get the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, lstat 'C:\...\AppData\Roaming\npm\node_modules\node-matrix-bundler-cli\js'
```

When I run an absolute URL for --entry, it works fine.

**Comment by joshgillies** [comment]
Nice, thanks for pointing this out!

I expect it's to do with the following line: https://github.com/joshgillies/node-matrix-bundler-cli/blob/master/index.js#L44

It's possible that replacing `__dirname` with something like `process.cwd()`, could be the fix here.

I'll take a look at a few options correct this behaviour under Windows.
